### ISSUE TITLE
How to debug winafl with vs2017

### ISSUE THREAD

**Issue by jinyu00** [googleprojectzero/winafl#148]
How to debug winafl with vs2017

**Comment by jinyu00** [comment]
I want to debug winafl with source , how can i do it with vs2017 or other debugger?

**Comment by ifratric** [comment]
By "debug WinAFL" I assume you mean the WinAFL DynamoRIO client (WinAFL.dll) since all other components are trivial to debug (cmake generates VS project/solution files and you can go from there). 

When it comes to the DynamoRIO client, I'm afraid the answer is "no". You can see some tips on DynamoRIO debugging at https://github.com/DynamoRIO/dynamorio/wiki/Debugging. Most of the time though I find it more convenient to just dump stuff I'm interested in into the debug log such as in https://github.com/googleprojectzero/winafl/blob/master/winafl.c#L664.

**Comment by Flyour** [comment]
when i debug alf-fuxx  with vs2017 , I get this error  "Source information is missing from debugging information for this module "，what  should i do ?

**Comment by Flyour** [comment]
> when i debug alf-fuxx with vs2017 , I get this error "Source information is missing from debugging information for this module "，what should i do ?

ok, I solved it,  add two  parameters to  our vs project:   /ZI   /JMC

**Comment by ifratric** [comment]
Glad you solved it! I think the DR client project (winafl.dll) might be messing up the vs flags for other projects in the same directory, so possibly could also be resolved by running cmake without `-DDynamoRIO_DIR` (which doesn't generate the winafl.dll project). Though of course your solution is better if you want to have all projects ready to build.
