### ISSUE TITLE
does the instrument_edge_coverage function work properly

### ISSUE THREAD

**Issue by jinyu00** [googleprojectzero/winafl#171]
Hi, I want to use the edge coverage, and I found an issue
```
https://github.com/googleprojectzero/winafl/issues/5

. The problem is that if any of the coverage modules executes two or more threads at the same time, every new context switch is going to be (wrongly) interpreted as new coverage.
```
The bug comment on that is fixed? 
And does the instrument_edge_coverage function work properly?

Thanks!

**Comment by ifratric** [comment]
Yes, it does work properly :-) A lot has changed since then, essentially now the previous offset is stored per-thread so context-switching should play no role. Additionally there is also the `-thread_coverage` instrumentation option which limits the coverage collection to only the thread that executes the target function.
