### ISSUE TITLE
You forgot to close the handle to the .cur_input file

### ISSUE THREAD

**Issue by Flyour** [googleprojectzero/winafl#237]
Between the write_to_testcase()  and  run_target()  function,  I think you should close the handle to the .cur_input file

**Comment by ifratric** [comment]
Hmm, won't it be closed in https://github.com/googleprojectzero/winafl/blob/master/afl-fuzz.c#L2723

**Comment by Flyour** [comment]
no.
if I don't use -f option , the out_file parameter  is NULL， so it won't close the handle...

**Comment by Flyour** [comment]
So forget to close the handle only if you don't use the -f option.

**Comment by ifratric** [comment]
out_file is also set if you have @@ in your command line here
https://github.com/googleprojectzero/winafl/blob/master/afl-fuzz.c#L7502

Otherwise, out_fd is used that is supposed to be persistent according to
https://github.com/googleprojectzero/winafl/blob/master/afl-fuzz.c#L118
So it will get neither opened nor closed during iterations.

I believe all of this code is taken from AFL as is. Is there a reason why this should behave different in WinAFL than in AFL?

**Comment by Flyour** [comment]
I get it. 
I did not use the -f option, but I did not use '@@'.  so when I open the .cur_input file in  pre_fuzz_handler function, it failed.
