### ISSUE TITLE
Target_offset Issue

### ISSUE THREAD

**Issue by mouLm** [googleprojectzero/winafl#248]
I have a C++ program built using eclipse 2019-03. The main method of this function reads the argument (input file) and passes it to the target function that I need to fuzz. 
The program is running normally. Following the steps provided in 
[https://github.com/googleprojectzero/winafl/blob/master/README.md](url) and [https://github.com/googleprojectzero/winafl/blob/master/readme_dr.md ](url)
I started with testing whether my program runs with DynamoRio. I couldn't get the offset of my target method using WinDbg, as shown in the image, it is not returning anything. 
![image](https://user-images.githubusercontent.com/63367767/80877772-6d470300-8c89-11ea-95f9-ce3b8d810198.png)

I tried debugging this issue and couldn't figure out why it is not returning the offsets. I extracted the offset from the project map file and validated its value from IDAPro. 
When I run the command 
D:\DynamoRIO-Windows-8.0.18377\bin32\drrun.exe -c winafl.dll -debug -target_module rusefi_simulator.exe -target_offset 0x4323f0 -fuzz_iterations 10 -nargs 1 -- rusefi_simulator.exe out\.cur_input

In the log file (attached), I get the "Target function was never called. Incorrect target_offset?"
[afl.rusefi_simulator.exe.15652.0000.proc.log](https://github.com/googleprojectzero/winafl/files/4568631/afl.rusefi_simulator.exe.15652.0000.proc.log)

Any reason why the DynamoRIO is not able to locate the offset. I am not sure if this is also related to Windbg issue.

**Comment by ifratric** [comment]
For symbols in WinDBG, ensure that the .pdb files got generated during the build process and are in the same directory as the .exe

For offset, note that it should be offset from the start of the module. The offset value you provided (0x4323f0) looks like the absolute value rather than the offset (from the screenshot you provided, the entire module is 0xff000 bytes in size). If 0x4323f0 is the absolute address, and start of the module is at 0x400000, then the correct offset would be 0x323f0.

**Comment by mouLm** [comment]
Thank you, it worked.
